name: Pre-release (test deployment)
on:
  push:
    branches:
      - main

concurrency:
  group: ci-pre-release
  cancel-in-progress: true

jobs:
  administration:
    runs-on: ubuntu-latest
    steps:
      - name: Draft Release
        id: draft-release
        uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: true
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      tag_name: ${{ steps.draft-release.outputs.tag_name }}
