name: Pull Request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ci-${{ github.head_ref }}-pr

jobs:
  administration:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: PR Labeling
        uses: srvaroa/labeler@v1.13.0
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
  validate:
    uses: ./.github/workflows/validate.yml
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
