name: Release
on:
  release:
    types:
      - published

concurrency:
  group: ci-release
  cancel-in-progress: true

jobs:
  promote_release:
    uses: ./.github/workflows/promote-release.yml
    with:
      type: latest
      ref: ${{ github.event.release.tag_name }}

  link-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}
      - name: Create Linear release
        uses: linear/linear-release-action@c0cb8354a362c24c6d3e0948f37fd66d07588e3f # v0.14.5
        with:
          access_key: ${{ secrets.LINEAR_ACCESS_KEY }}
          name: ${{ github.event.repository.name }} (${{ github.event.release.tag_name }})
          version: ${{ github.event.release.tag_name }}
          links: ${{ github.event.release.html_url }}
