name: Release
on:
  release:
    types:
      - published

concurrency:
  group: ci-release
  cancel-in-progress: true

jobs:
  promote_release:
    uses: ./.github/workflows/promote-release.yml
    with:
      type: latest
      ref: ${{ github.event.release.tag_name }}

  link-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}
      - name: Create Linear release
        uses: linear/linear-release-action@e01367f7b3c3a18868a4aab21ea6fdae80430050 # v0.14.2
        with:
          access_key: ${{ secrets.LINEAR_ACCESS_KEY }}
          name: ${{ github.event.repository.name }} (${{ github.event.release.tag_name }})
          version: ${{ github.event.release.tag_name }}
          links: ${{ github.event.release.html_url }}
